//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalAccountsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListEntity
    {
        public ListEntity()
        {
            this.ListItems = new HashSet<ListItemEntity>();
        }
    
        public int ListID { get; set; }
        public string ListName { get; set; }
        public int GroupsGroupID { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual ICollection<ListItemEntity> ListItems { get; set; }
    }
}
