//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalAccountsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListItemEntity
    {
        public int ListItemID { get; set; }
        public string Name { get; set; }
        public string IsChecked { get; set; }
        public string CreatedDate { get; set; }
        public int ListEntityListID { get; set; }
    
        public virtual ListEntity ListEntity { get; set; }
    }
}
